Repository patrickcping/pingone-go-sdk-v2, pull requests merged in 2023-11, with the labels that each got.

#278 Added the `InspectionType` property to the `GovernmentIdConfiguration…
  CHANGELOG.md
  verify/.openapi-generator/FILES
  verify/.version
  verify/CHANGELOG.md
  verify/README.md
  verify/api/openapi.yaml
  verify/configuration.go
  verify/docs/EnumInspectionType.md
  verify/docs/GovernmentIdConfiguration.md
  verify/generate/pingone-verify.yml
  verify/go.mod
  verify/go.sum
  verify/model_enum_inspection_type.go
  verify/model_government_id_configuration.go
Labels: enhancement

#280 bump pingone modules 2023-11-10
  CHANGELOG.md
  go.mod
  go.sum
  go.work.sum
Labels: dependencies, go

#289 Fix invalid value for `EnumMFADevicePolicySelection` model
  CHANGELOG.md
  mfa/.version
  mfa/CHANGELOG.md
  mfa/README.md
  mfa/api/openapi.yaml
  mfa/configuration.go
  mfa/docs/EnumMFADevicePolicySelection.md
  mfa/generate/pingone-mfa.yml
  mfa/go.mod
  mfa/go.sum
  mfa/model_enum_mfa_device_policy_selection.go
Labels: bug

#291 Adjust CORS origins documentation
  CHANGELOG.md
  management/.version
  management/CHANGELOG.md
  management/README.md
  management/api/openapi.yaml
  management/configuration.go
  management/docs/ApplicationCorsSettings.md
  management/generate/pingone-management.yml
  management/model_application_cors_settings.go
Labels: documentation
